services:
  - type: web
    name: artisan-platform-backend
    runtime: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    # buildCommand/startCommand are ignored for docker runtime, so remove them
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: artisan-platform-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "alx-project-nexus-1.onrender.com,localhost"
    healthCheckPath: /healthz   # add a tiny view for this if you like

databases:
  - name: artisan-platform-db
    databaseName: artisan_db
    user: artisan_user
