services:
  - type: web
    name: artisan-platform-backend
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: artisan-platform-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: artisan_db
    databaseName: artisan_db
    user: artisan_user
